# Generated by Django 3.1.7 on 2021-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='CardID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='CardPan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='City',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='Expiration',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='State',
            field=models.CharField(max_length=30),
        ),
    ]
