# Generated by Django 3.1.7 on 2021-03-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManager', '0002_auto_20210318_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='Amount',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='CVV',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='CardID',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='CardPan',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='City',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='Expiration',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='Name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='State',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='ZipCode',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
