# Generated by Django 3.1.7 on 2021-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManager', '0003_auto_20210320_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='card',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='card',
            name='CVV',
        ),
        migrations.RemoveField(
            model_name='card',
            name='CardPan',
        ),
        migrations.RemoveField(
            model_name='card',
            name='City',
        ),
        migrations.RemoveField(
            model_name='card',
            name='Expiration',
        ),
        migrations.RemoveField(
            model_name='card',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='State',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ZipCode',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='City',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='State',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='Street',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='ZipCode',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='ProductValue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
