# Generated by Django 3.1.7 on 2021-03-17 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testnobodypythpnbot', '0002_auto_20210311_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Satoshi', models.IntegerField()),
                ('PaidSatoshi', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('Time', models.IntegerField()),
                ('TXID', models.CharField(blank=True, max_length=250, null=True)),
                ('Address', models.CharField(max_length=250)),
                ('ProductItem', models.CharField(max_length=100)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testnobodypythpnbot.telegramuser')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
