# Generated by Django 3.1.7 on 2021-03-11 19:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('testnobodypythpnbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='telegramuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
